export const server = "http://localhost:8000/";
export const register = server + "api/register";
export const login = server + "api/login";
export const addProduct = server + "api/addProduct";
export const getProducts = server + "api/getProducts";
export const deleteProduct = server + "api/deleteProduct";
export const getSingleProduct = server + "api/getSingleProduct";
export const updateProduct = server + "api/updateProduct";
export const search = server + "api/search";
